# -*- coding: utf-8 -*-
"""dataplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eMMv1MpnnUUefkhzc9rDipGCXepsmCb2
"""

from google.colab import drive
drive.mount('/content/drive')

import matplotlib.pyplot as plt
import numpy as np

data = np.genfromtxt('/content/drive/MyDrive/log.csv', delimiter=',')

epoch = data[1:, 0]
losstr = data[1:, 1]
losste = data[1:, 2]
ioutr = data[1:, 3]
ioute = data[1:, 4]

plt.plot(epoch, losstr)
plt.xlabel("Epochs")
plt.ylabel("Training Loss")
plt.show()

plt.plot(epoch, losste)
plt.xlabel("Epochs")
plt.ylabel("Testing Loss")
plt.show()

plt.plot(epoch, ioutr)
plt.xlabel("Epochs")
plt.ylabel("Training IoU")
plt.show()

plt.plot(epoch, ioute)
plt.xlabel("Epochs")
plt.ylabel("Testing IoU")
plt.show()